service: lambda-repush_handler

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-pseudo-parameters
  - serverless-offline

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  env:
    LAMBDA_STAGE: ${self:provider.stage}
    SM_AWS_ACCOUNT: ${ssm:/simple-dealer/${self:provider.stage}/aws_account_id}
    SM_AWS_REGION: ${ssm:/simple-dealer/${self:provider.stage}/aws_account_region}
  serverless-offline:
    babelOptions:
      presets: ['env']

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'da'}
  region: us-east-1
  environment: ${self:custom.env}
  # iamRoleStatements:

functions:
  handler:
    handler: handler.init
    role: arn:aws:iam::577195013332:role/executing-lambda
    events:
      - http:
          path: repush
          method: get
          cors: true
      - http:
          path: repush
          method: post
          cors: true
